@MinimalAPI_HostAddress = https://localhost:7064

POST {{MinimalAPI_HostAddress}}/api/rooms

###

GET {{MinimalAPI_HostAddress}}/api/rooms

###

GET {{MinimalAPI_HostAddress}}/api/rooms/{roomId}

###

POST {{MinimalAPI_HostAddress}}/api/rooms/{roomId}/players

###

POST {{MinimalAPI_HostAddress}}/api/scores/{roomId}

###

POST {{MinimalAPI_HostAddress}}/api/users

###

GET {{MinimalAPI_HostAddress}}/api/users/{username}

###
